### PR TITLE
Makes quadratic_has_solution non-branching

### PR DESCRIPTION
**Pull request by pmj**
This might improve performance as the compiler should be able to compile this down to entirely non-branching code.

See also discussion here: https://twitter.com/pmjordan/status/1388437558745513986

### CODE REVIEW

**Comment by KayEss** [comment]
This gives a net slow down:
```
"spheres-white.tga" 1920x1080 225/225 (128x72)
"spheres-white.tga" 1920x1080 225/225 (128x72)
"spheres-white.tga" 1920x1080 225/225 (128x72)
"spheres-white.tga" 1920x1080 225/225 (128x72)
"spheres-white.tga" 1920x1080 225/225 (128x72)

 Performance counter stats for './build.tmp/clang-release/scenes/early/spheres-white -w 1920 -h 1080 -c 100 -s 20' (5 runs):

        290,831.68 msec task-clock                #   15.377 CPUs utilized            ( +-  0.03% )
            49,883      context-switches          #    0.172 K/sec                    ( +-  1.30% )
                18      cpu-migrations            #    0.000 K/sec                    ( +- 15.63% )
             3,538      page-faults               #    0.012 K/sec                    ( +-  0.02% )
 1,364,927,525,834      cycles                    #    4.693 GHz                      ( +-  0.02% )
 1,788,681,365,813      instructions              #    1.31  insn per cycle           ( +-  0.00% )
   119,696,978,021      branches                  #  411.568 M/sec                    ( +-  0.00% )
       485,260,337      branch-misses             #    0.41% of all branches          ( +-  0.74% )

           18.9132 +- 0.0347 seconds time elapsed  ( +-  0.18% )


real    1m34.620s
user    24m11.920s
sys     0m2.526s
```
I kept the initial branch so that it's not performing the whole calculation every time, but kept your removal of the final set of `if` statements. This gave me about a 2% improvement:

```
"spheres-white.tga" 1920x1080 225/225 (128x72)
"spheres-white.tga" 1920x1080 225/225 (128x72)
"spheres-white.tga" 1920x1080 225/225 (128x72)
"spheres-white.tga" 1920x1080 225/225 (128x72)
"spheres-white.tga" 1920x1080 225/225 (128x72)

 Performance counter stats for './build.tmp/clang-release/scenes/early/spheres-white -w 1920 -h 1080 -c 100 -s 20' (5 runs):

        236,976.27 msec task-clock                #   15.343 CPUs utilized            ( +-  0.05% )
            41,145      context-switches          #    0.174 K/sec                    ( +-  0.38% )
                13      cpu-migrations            #    0.000 K/sec                    ( +- 12.17% )
             3,538      page-faults               #    0.015 K/sec                    ( +-  0.04% )
 1,111,913,801,619      cycles                    #    4.692 GHz                      ( +-  0.04% )
 1,604,887,580,121      instructions              #    1.44  insn per cycle           ( +-  0.00% )
    97,278,068,687      branches                  #  410.497 M/sec                    ( +-  0.00% )
       440,252,419      branch-misses             #    0.45% of all branches          ( +-  1.91% )

           15.4449 +- 0.0283 seconds time elapsed  ( +-  0.18% )


real    1m17.306s
user    19m43.084s
sys     0m2.047s
```

**Comment by pmj** [comment]
Yup, makes sense that skipping the sqrt despite the branch can be a net gain.

I'd really have to dig into the whole codebase and fine grained perf data to say where you can improve it.

**Comment by KayEss** [comment]
For me this was mainly an exercise in getting a bit more familiar with perf rather than trying to make this particular scene faster to render. I was actually expecting to find that it was the matrix maths that was slow and I was going to replace it with some intrinsics or SIMD or something and see how the difference come out. Maybe in a different scene that will be the case.

**Comment by pmj** [comment]
>  I was actually expecting to find that it was the matrix maths that was slow and I was going to replace it with some intrinsics or SIMD or something and see how the difference come out.

I don't have much hands-on experience with ray tracing, but my understanding is that the expensive bit is finding ray-surface intersections. I assume that's what this quadratic solver is about?

**Comment by KayEss** [comment]
The first thing is to work out which geometry the camera can see. From there the illumination has to be integrated -- this includes rays from reflections and also which lights are illuminating the hit location -- because there are multiple lights in this scene that means the majority of rays are checking light visibility. The scene only features spheres and as we don't care where the ray hits geometry the occlusion test only needs to see if there are solutions to the quadratic and we don't care what the solutions are.

The function identified by perf with 25% of the runtime is this one https://github.com/KayEss/AnimRay/blob/main/include/animray/geometry/collection.hpp#L91-L99 which is looping through the spheres in the scene checking if any occlude each light source. It looks like the compiler has inlined pretty much everything that comprises the actual tests, which is nice.

**Pull request merged**
